language: dtd


os:
  - linux


before_install:
  - wget https://github.com/htacg/tidy-html5/releases/download/5.2.0/tidy-5.2.0-64bit.deb
  - sudo dpkg --install --force-all tidy-5.2.0-64bit.deb


addons:
  apt:
    packages:
      - libxml2-utils
      - libxml-xpath-perl
      - xsltproc
      - shunit2


script:
  - make check
