language: dtd


os:
  - linux


before_install:
  - wget https://github.com/htacg/tidy-html5/releases/download/5.2.0/tidy-5.2.0-64bit.deb
  - echo -n "3eb446058a6eece732c4fe835063805af7b2bcc16c19f8ee830e7493a2e17da0  tidy-5.2.0-64bit.deb" | sha256sum --check
  - sudo dpkg --install --force-all tidy-5.2.0-64bit.deb


addons:
  apt:
    packages:
      - libxml2-utils
      - libxml-xpath-perl
      - xsltproc
      - shunit2


script:
  - make check
